const userClickedPattern=[];
var gamePattern=[];
var buttonColors=["red","blue","green","yellow"];
var number;
var randomChosenColor;
function compPattern(){
    number=Math.floor(Math.random()*4);
    randomChosenColor=buttonColors[number];
    gamePattern.push(randomChosenColor);
    playSound(randomChosenColor);
    console.log(gamePattern);
}
function userPattern(){
        $(".btn").off("click").on("click",function(event){
            var buttonId=event.target.id;
            console.log(buttonId);
            userClickedPattern.push(buttonId);
            console.log(userClickedPattern);
            playSound(buttonId);
            checkAnswer();
        });

    
}

function playSound(color){
    $("#"+color).fadeIn(100).fadeOut(100).fadeIn(100);
    var audio=new Audio("sounds/"+color+".mp3");
    audio.play()
    .then(() => {
        console.log('Audio is playing:'+color);
    })
    .catch(error => {
        console.error('Error while playing audio:', error);
    });
}

var l=1;

function checkAnswer(){
    for(var i=0;i<userClickedPattern.length;i++){
        if(gamePattern[i]!==userClickedPattern[i]){
            console.log("incorrect");
            gamePattern = [];
            userClickedPattern.splice(0, userClickedPattern.length);
            var overlay = $("<div></div>").css({
                position: "fixed",
                top: 0,
                left: 0,
                width: "100%",
                height: "100%",
                backgroundColor: "white", 
                zIndex: 9999 
            }).appendTo("body");
            overlay.fadeIn(100).fadeOut(100).fadeIn(100, function() {
                overlay.remove();
            });

            $("#level-title").text("Press A Key To Start");
            l=1;
            return;
        }
    }

        if (userClickedPattern.length === gamePattern.length) {
            console.log("Correct sequence!");
            userClickedPattern.splice(0, userClickedPattern.length);
            $("#level-title").text("Level "+l);
            l++;
            setTimeout(function () {
                compPattern();
            }, 1000);
    
}
}
function startGame(){
    compPattern();
    userPattern();
    
}
document.addEventListener("keypress", startGame);

// // Define the game pattern array to store the sequence of colors generated by the system
// const userClickedPattern = [];
// var gamePattern = [];
// var buttonColors = ["red", "blue", "green", "yellow"];
// var number;
// var randomChosenColor;

// // Function to generate a random color and add it to the game pattern
// function compPattern() {
//     number = Math.floor(Math.random() * 4);
//     randomChosenColor = buttonColors[number];
//     gamePattern.push(randomChosenColor);
//     playSound(randomChosenColor);
//     console.log(gamePattern);
// }

// // Function to handle user clicks on colors
// $(".btn").on("click", function(event) {
//     var buttonId = event.target.id;
//     console.log(buttonId);
//     userClickedPattern.push(buttonId);
//     console.log(userClickedPattern);
//     playSound(buttonId);
//     checkAnswer(); // Check the user's answer after each click
// });

// // Function to play sound for a color
// function playSound(color) {
//     $("#" + color).fadeIn(100).fadeOut(100).fadeIn(100);
//     var audio = new Audio("sounds/" + color + ".mp3");
//     audio.play()
//         .then(() => {
//             console.log('Audio is playing: ' + color);
//         })
//         .catch(error => {
//             console.error('Error while playing audio:', error);
//         });
// }

// // Function to check if the user's clicked pattern matches the game pattern
// function checkAnswer() {
//     // Check if the user's clicked pattern matches the game pattern
//     for (var i = 0; i < userClickedPattern.length; i++) {
//         if (gamePattern[i] !== userClickedPattern[i]) {
//             console.log("Incorrect color!");
//             userClickedPattern.splice(0, userClickedPattern.length); // Clear the user's clicked pattern
//             return; // Exit the function if the colors don't match
//         }
//     }

//     // If the user's clicked pattern matches the game pattern
//     if (userClickedPattern.length === gamePattern.length) {
//         console.log("Correct sequence!");
//         userClickedPattern.splice(0, userClickedPattern.length); // Clear the user's clicked pattern

//         // Continue the game by generating the next color
//         setTimeout(function () {
//             compPattern();
//         }, 1000); // Wait for 1 second before generating the next color
//     }
// }

// // Function to start the game when a key is pressed
// function startGame() {
//     compPattern(); // Generate the first color pattern
// }

// // Call startGame() to begin the game when a key is pressed
// document.addEventListener("keypress", startGame);
